<h1>Registration</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('home/register'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('passwordConfirm'));
echo $this->formRow($form->get('captcha'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>