<?php if(isset($this->messages[0])) { ?>
<div class="message">
    <?php echo $this->messages[0]; ?>
</div>
<?php } ?>

<table>
    <tr>
    <th>User</th>
    <th></th>
    </tr>
<?php foreach ($users as $user) {?>
    <tr>
        <td><?php echo $user['username'];?></td>
        <td><a href="<?php echo $this->url('home/users/users_delete', array('id' => $user['id']));?>">Delete</a></td>
    </tr>
<?php } ?>
</table>
